# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muni', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='frontpage.Muni')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.State')),
            ],
        ),
    ]
