# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 23:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20170601_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='muni',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='frontpage.Muni'),
        ),
    ]
