# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_auto_20170601_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontpage.State')),
            ],
        ),
        migrations.RemoveField(
            model_name='muni',
            name='state',
        ),
        migrations.AlterField(
            model_name='location',
            name='muni',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='county', chained_model_field='county', on_delete=django.db.models.deletion.CASCADE, to='frontpage.Muni'),
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', default=0, on_delete=django.db.models.deletion.CASCADE, to='frontpage.County'),
        ),
        migrations.AddField(
            model_name='muni',
            name='county',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='frontpage.County'),
        ),
    ]
